/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time
package main

import "{{ .PkgName }}/cmd"

func main() {
	cmd.Execute()
}
