/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time

package cmd

import (
	"fmt"
	"time"
)

var cfg Config

type Config struct {
	EventBus EventBusConfig `yaml:"eventBus" mapstructure:"eventBus"`
	Client ClientConfig `yaml:"client" mapstructure:"client"`
	Metrics MetricsConfig `yaml:"metrics" mapstructure:"metrics"`
}

type MetricsConfig struct {
	Enabled bool `yaml:"enabled" mapstructure:"enabled"`
}

func (m MetricsConfig) String() string {
	if m.Enabled {
		return "Metrics enabled"
	} else {
		return "Metrics disabled"
	}
}

type ClientConfig struct {
	Timeout time.Duration `yaml:"timeout" mapstructure:"timeout"`
	RetryCount int `yaml:"retryCount" mapstructure:"retryCount"`
	Backoff BackoffParams `yaml:"backoff" mapstructure:"backoff"`
}

func (c ClientConfig) String() string {
	return fmt.Sprintf("Client: timeout=%v retryCount=%d backoff=%s backoffDelay=%v",
		c.Timeout,
		c.RetryCount,
		c.Backoff.Type,
		c.Backoff.Delay,
	)
}

type BackoffParams struct {
	Type string `yaml:"type" mapstructure:"type"`
	Delay time.Duration `yaml:"delay" mapstructure:"delay"`
	Multiplier *uint `yaml:"multiplier" mapstructure:"multiplier"`
}

type EventBusConfig struct {
	Type string `yaml:"type" mapstructure:"type"`
	Nats NatsConfig `yaml:"nats" mapstructure:"nats"`
}

func (e EventBusConfig) String() string {
	return fmt.Sprintf("Using %s event bus: %s, secure: %v", e.Type, e.Nats.URL, e.Nats.Secure)
}

type NatsConfig struct {
	URL string `yaml:"url" mapstructure:"url"`
	Secure bool `yaml:"secure" mapstructure:"secure"`
	TLS TLSConfig `yaml:"tls" mapstructure:"tls"`
	Topics Topics `yaml:"topics" mapstructure:"topics"`
}

type TLSConfig struct {
	CAPath string `yaml:"ca" mapstructure:"ca"`
	KeyPath string `yaml:"key" mapstructure:"key"`
	CertPath string `yaml:"crt" mapstructure:"crt"`
	Verify string `yaml:"verify" mapstructure:"verify"`
}

type Topics struct {
	DLQ TopicConfig `yaml:"dlq" mapstructure:"dlq"`
	ResponseTopic TopicConfig `yaml:"resp" mapstructure:"resp"`
}

type TopicConfig struct {
	Name string `yaml:"name" mapstructure:"name"`
}
