/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time

package cmd

import (
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"time"
)

type Config struct {
	EventBus EventBusConfig `yaml:"eventBus"`
	Client ClientConfig `yaml:"client"`
	Metrics MetricsConfig `yaml:"metrics"`
}

type MetricsConfig struct {
	Enabled bool `yaml:"enabled"`
}

type ClientConfig struct {
	Timeout time.Duration `yaml:"timeout"`
	RetryCount int `yaml:"retryCount"`
	Backoff BackoffParams `yaml:"backoff"`
}

type BackoffParams struct {
	Type string `yaml:"type"`
	Delay time.Duration `yaml:"delay"`
	Multiplier *uint `yaml:"multiplier"`
}

type EventBusConfig struct {
	Type string `yaml:"type"`
	Nats NatsConfig `yaml:"nats"`
}

type NatsConfig struct {
	URL string `yaml:"url"`
	Secure bool `yaml:"secure"`
	TLS TLSConfig `yaml:"tls"`
	Topics Topics `yaml:"topics"`
}

type TLSConfig struct {
	CAPath string `yaml:"ca"`
	KeyPath string `yaml:"key"`
	CertPath string `yaml:"crt"`
	Verify string `yaml:"verify"`
}

type Topics struct {
	DLQ TopicConfig `yaml:"dlq"`
	ResponseTopic TopicConfig `yaml:"resp"`
}

type TopicConfig struct {
	Name string `yaml:"name"`
}
