/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time

package cmd

import (
	"fmt"
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"time"
)

var cfg Config

type Config struct {
	EventBus EventBusConfig `yaml:"eventBus"`
	Client ClientConfig `yaml:"client"`
	Metrics MetricsConfig `yaml:"metrics"`
}

type MetricsConfig struct {
	Enabled bool `yaml:"enabled"`
}

func (m MetricsConfig) String() string {
	if m.Enabled {
		return "Metrics enabled"
	} else {
		return "Metrics disabled"
	}
}

type ClientConfig struct {
	Timeout time.Duration `yaml:"timeout"`
	RetryCount int `yaml:"retryCount"`
	Backoff BackoffParams `yaml:"backoff"`
}

func (c ClientConfig) String() string {
	return fmt.Sprintf("Client: timeout=%v retryCount=%d backoff=%s backoffDelay=%v",
		c.Timeout,
		c.RetryCount,
		c.Backoff.Type,
		c.Backoff.Delay,
	)
}

type BackoffParams struct {
	Type string `yaml:"type"`
	Delay time.Duration `yaml:"delay"`
	Multiplier *uint `yaml:"multiplier"`
}

type EventBusConfig struct {
	Type string `yaml:"type"`
	Nats NatsConfig `yaml:"nats"`
}

func (e EventBusConfig) String() string {
	return fmt.Sprintf("Using %s event bus: %s, secure: %v", e.Type, e.Nats.URL, e.Nats.Secure)
}

type NatsConfig struct {
	URL string `yaml:"url"`
	Secure bool `yaml:"secure"`
	TLS TLSConfig `yaml:"tls"`
	Topics Topics `yaml:"topics"`
}

type TLSConfig struct {
	CAPath string `yaml:"ca"`
	KeyPath string `yaml:"key"`
	CertPath string `yaml:"crt"`
	Verify string `yaml:"verify"`
}

type Topics struct {
	DLQ TopicConfig `yaml:"dlq"`
	ResponseTopic TopicConfig `yaml:"resp"`
}

type TopicConfig struct {
	Name string `yaml:"name"`
}
