/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time

package cmd

import (
	"context"
	"{{ .PkgName }}/proto"
	"encoding/json"
	"net/http"
)

func decodeParams[T any](v interface{}) (*T, error) {
	data, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var out T
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

type OperationFunc func(ctx context.Context, client *proto.Client, params interface{}) (*http.Response, error)

var operations = map[string]OperationFunc{
{{- range .Operations }}
	"{{ . }}": func(ctx context.Context, client *proto.Client, params interface{}) (*http.Response, error) {
		p, err := decodeParams[proto.{{ . | title }}Params](params)
		if err != nil {
			return nil, err
		}

		return client.{{ . | title }}(ctx, p)
	},
{{- end }}
}
