/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time

package cmd

import (
	"context"
	"{{ .PkgName }}/proto"
	"encoding/json"
	"net/http"
)

type ClientWrapper struct {
	client *proto.Client
}

{{- range $op, $parameters := .Operations }}

func (c ClientWrapper) {{ $op | title }} (ctx context.Context, params map[string]interface{}) (*http.Response, error) {
	{{- $pathParams := "" }}
	{{- $otherParams := "" }}
	{{- range $i, $param := $parameters.Path }}
	{{ $param.Name }}, ok := params["{{ $param.Name }}"].({{ $param.Type }})
	if !ok {
		{{- if $param.Required }}
		return nil, fmt.Errorf("{{ $param.Name }} is required in path")
		{{- else }}
		log.Warn("{{ $param.Name }} does not exist or has a wrong type")
		{{- end }}
	}
		{{- $pathParams = printf "%s, %s" $pathParams $param.Name }}
	{{- end }}
	{{- if gt (len $parameters.Other) 0 }}
	var p {{ $op }}Params
	{{- range $i, $param := $parameters.Other }}
	{{- $isPointer := "" }}
	{{- if not $param.Required }}
	{{- $isPointer = "*" }}
	{{- end }}
	p.{{ $param.Name }}, _ = params["{{ $param.Name }}"].({{ $isPointer }}{{ $param.Type }})
	{{- end }}
	{{- $otherParams = printf ", p"}}
	{{- end }}
	return c.client.{{ $op | title }}(ctx{{ $pathParams }}{{ $otherParams }})
}
{{- end }}
