/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time

package cmd

import (
	"context"
	"{{ .PkgName }}/proto"
	"encoding/json"
	"net/http"
)

func decodeParams[T any](v interface{}) (*T, error) {
	data, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var out T
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

type ClientWrapper struct {
	client *proto.Client
}

{{- range $op, $parameters := .Operations }}

func (c ClientWrapper) {{ $op | title }} (ctx context.Context, params interface{}) (*http.Response, error) {
{{- if eq (len $parameters) 0 }}
	return c.client.{{ $op | title }}(ctx)
{{- else }}
	p, err := decodeParams[proto.{{ $op | title }}Params](params)
	if err != nil {
		return nil, err
	}

	return c.client.{{ $op | title }}(ctx, p)
{{- end }}
}
{{- end }}
