/*
{{ .Copyright }}
{{ if .Legal.Header }}{{ .Legal.Header }}{{ end }}
*/
// DO NOT EDIT!!!
// This file is autogenerated and will be overwritten next time

package cmd

import (
	context "context"
	json "encoding/json"
	yaml "go.yaml.in/yaml/v3"
	proto "{{ .PkgName }}/proto"
	prototext "google.golang.org/protobuf/encoding/prototext"
)

type Sender struct {
	proto.UnimplementedTriggerServer
}

func (s Sender) FetchResource(ctx context.Context,
	in *proto.FetchResourceRequest) (*proto.FetchResourceResponse, error) {
	log.Infof("FetchResource called with %s", prototext.Format(in))
	var input interface{}
	err := yaml.Unmarshal(in.Resource, &input)
    	if err != nil {
        	return nil, err
    	}
	raw, err := json.Marshal(input)
    	if err != nil {
        	return nil, err
    	}
	return &proto.FetchResourceResponse{
		// For now it doesn't fetch anything
		Resource: raw,
	}, nil
}

func (s Sender) Execute(ctx context.Context,
	in *proto.ExecuteRequest) (*proto.ExecuteResponse, error) {
	log.Infof("Execute called with %s", prototext.Format(in))
	log.Infof("Resource: %s", in.Resource)
	log.Infof("Payload: %s", in.Payload)
	return &proto.ExecuteResponse{
		// For now it doesn't execute anything
		Response: []byte("success execute"),
	}, nil
}

func (s Sender) ApplyPolicy(ctx context.Context,
	in *proto.ApplyPolicyRequest) (*proto.ApplyPolicyResponse, error) {
	log.Infof("ApplyPolicy called with %s", prototext.Format(in))
	return &proto.ApplyPolicyResponse{
		Success: true,
		Message: "success",
	}, nil
}
